server:
  port: 8070
spring:
  application:
    name: "gateway-svc"
  config:
    import: "configserver:http://${CONFIG_SVC_HOST:localhost}:8888"
  rabbitmq:
    host: "${RABBITMQ_HOST:localhost}"
    port: 5672
    username: "${RABBITMQ_USERNAME}"
    password: "${RABBITMQ_PASSWORD}"
  cloud:
    bus:
      enabled: true
    stream:
      defaultBinder: rabbit
    gateway:
      routes:
        - id: resource-service
          uri: lb://resource-svc
          predicates:
            - Path=/resources/**
        - id: song-service
          uri: lb://song-svc
          predicates:
            - Path=/songs/**
        - id: eureka-service
          uri: lb://eureka-svc
          predicates:
            - Path=/eureka-svc/**
        - id: config-service
          uri: lb://config-svc
          predicates:
            - Path=/config-svc/**
        - id: resource-proc-service
          uri: lb://resource-proc
          predicates:
            - Path=/resource-proc/**
        - id: resource-proc-health
          uri: lb://resource-proc
          predicates:
            - Path=/resource-proc/health/**
        - id: resource-svc-health
          uri: lb://resource-svc
          predicates:
            - Path=/resource-svc/health/**
        - id: song-svc-health
          uri: lb://song-svc
          predicates:
            - Path=/song-svc/health/**
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: bus-refresh, health, info, env
      base-path: /
      path-mapping:
        health: gateway-svc/health
