server:
  port: 8888

spring:
  application:
    name: config-svc
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kirtananushka/microservices-fundamentals-config-repo
          clone-on-start: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, env
      base-path: /
      path-mapping:
        health: config-svc/health