server:
  port: 8073
logging:
  level:
    root: info
    org.springframework.retry: debug
    com.tananushka.resource.proc.service: info
    com.tananushka.resource.proc.service.ResourceProcessorService: debug
spring:
  application:
    name: "resource-proc"
  config:
    import: "configserver:"
  cloud:
    bus:
      enabled: true
    stream:
      defaultBinder: rabbit
      rabbit:
        binder:
          environment:
            spring:
              rabbitmq:
                host: "${RABBITMQ_HOST:localhost}"
                port: 5672
                username: "${RABBITMQ_USERNAME}"
                password: "${RABBITMQ_PASSWORD}"
  activemq:
    broker-url: "tcp://${ACTIVEMQ_HOST:localhost}:61616"
    user: "${ACTIVEMQ_USERNAME}"
    password: "${ACTIVEMQ_PASSWORD}"
queue:
  resource: "resource.queue"
svc:
  song-svc:
    name: "SONG-SVC"
    songs-endpoint: "/songs"
    health-endpoint: "/song-svc/health"
  resource-svc:
    name: "RESOURCE-SVC"
    resources-endpoint: "/resources/audiodata"
    health-endpoint: "/resource-svc/health"
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
retry:
  maxAttempts: 10
  delay: 1000
  multiplier: 2.0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: bus-refresh, health, info, env
      base-path: /
      path-mapping:
        health: resource-proc/health