server:
  port: 8761

logging:
  level:
    root: INFO
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka.server: DEBUG

spring:
  application:
    name: "eureka-svc"
  cloud:
    bus:
      enabled: true
    stream:
      defaultBinder: rabbit
      rabbit:
        binder:
          environment:
            spring:
              rabbitmq:
                host: "${RABBITMQ_HOST:localhost}"
                port: 5672
                username: "${RABBITMQ_USERNAME}"
                password: "${RABBITMQ_PASSWORD}"
                
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}"
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: eureka-svc/health
