server:
  port: 8072
logging:
  level:
    root: warn
    com.tananushka.song.svc: info
spring:
  application:
    name: "song-svc"
  config:
    import: "configserver:http://config-svc:8888"
  cloud:
    bus:
      enabled: true
    stream:
      defaultBinder: rabbit
      rabbit:
        binder:
          environment:
            spring:
              rabbitmq:
                host: "${RABBITMQ_HOST:localhost}"
                port: 5672
                username: "${RABBITMQ_USERNAME}"
                password: "${RABBITMQ_PASSWORD}"
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:5432/song_svc_db"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
  jpa:
    properties:
      hibernate:
        dialect=org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka/"
management:
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: db
  endpoints:
    web:
      exposure:
        include: bus-refresh, health, info, env
      base-path: /
      path-mapping:
        health: song-svc/health